### ISSUE TITLE
Move `app/` to `tests/`

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#104]
There's an `app/` folder that I used to manually test and later within my testsuite. It makes more sense to move this `app/` folder to the `tests/` directory.

**Comment by aidan-casey** [comment]
We run into a couple problems with this:

1. Where to put it. It doesn't make sense in the root of the tests directory, imo. But it also gets weird if you throw it in the integrations folder. Also not sure if that would cause composer problems since we'd have two PSR-4 namespaces in the same directory.

2. We are not loading from `autoload-dev` for Tempest. Giving it further thought though, it makes sense for that to only be a dev namespace _and_ I can think of scenarios where you might have a Tempest package only in development (e.g., debug bar, etc.)

**Comment by brendt** [comment]
> Where to put it. It doesn't make sense in the root of the tests directory, imo. But it also gets weird if you throw it in the integrations folder. Also not sure if that would cause composer problems since we'd have two PSR-4 namespaces in the same directory.

Doesn't this kind of mean the current structure is good-ish? It's already contained in a folder outside of `src`, and mimics a real-life project perfectly. 

I'm actually kind of inclined to keep it as-is for now, now that you've said this. It's definitely not in the way of 1.0, and there doesn't seem to be an alternative that's better.

> We are not loading from autoload-dev for Tempest. Giving it further thought though, it makes sense for that to only be a dev namespace and I can think of scenarios where you might have a Tempest package only in development (e.g., debug bar, etc.)

Good point, not for 1.0 but afterwards. I made an issue: https://github.com/tempestphp/tempest-framework/issues/182
