### ISSUE TITLE
Console formatter fails to autowire

### ISSUE THREAD

**Issue by aidan-casey** [tempestphp/tempest-framework#152]
By mistake, I found there is no initializer for the console formatter. For some reason autowiring is failing for this and the container cannot provide an instance.

**Comment by aidan-casey** [comment]
It seems like something is happening with singletons to cause them not to quite register correctly. I will look into this further.

**Comment by brendt** [comment]
This is because of legacy. The console formatter is registered in `Kernel::initContainer` as a singleton, I don't remember why that is. It's on my list to refactor this blob of code. 

Also, for testing, this singleton definition is overwritten in `TestCase::setup`, the idea being that `TestConsoleFormatter` strips away all console formatting, so that you don't have to deal with weird escape sequences during testing.

**Comment by aidan-casey** [comment]
@brendt it actually seems to be a bug with singletons. I don't recall what exactly I found last night, but I'll upload my notes today.

**Comment by brendt** [comment]
All of this should be fixed now ✅
