### ISSUE TITLE
Fix container logging for intializers and injected container calls

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#180]
See https://github.com/tempestphp/tempest-framework/pull/177/files#r1507660304

**Comment by aidan-casey** [comment]
So I actually had a working version of this. [This](https://github.com/tempestphp/tempest-framework/pull/163/commits/4cf22c8d1adc372f7315418d8f5d936716359e4a?diff=split&w=0#diff-a1a727f85cce9dce165fb86724f011872f22953af1b262bee962c293c819b313R33-R51) is an outdated form of that, I never committed the latest iteration.

Basically, because each "step"/"context" was keep a reference of the previous one, we were never losing the originator, as the tree could continue as long as necessary and would never reset the originator. The key is I was also completing steps, so it would throw away stuff that was successful and not relevant.

As I'm looking at it now, there's a chance we could just pull the origin by the first array key though. 🤔

**Comment by brendt** [comment]
> As I'm looking at it now, there's a chance we could just pull the origin by the first array key though. 🤔

Could you elaborate on that?

**Comment by aidan-casey** [comment]
Instead of storing the origin in a special property, track it by whatever is first in the array. 🙂

**Comment by brendt** [comment]
Believe it or not, this now works
