### ISSUE TITLE
File support in requests

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#201]

**Comment by yassiNebeL** [comment]
I understand that, the `GenericRequest` class doesn't handles uploaded files yet, So far, do you mean a dedicated file class for that, like you did with the Cookie?

Can you please assign this to me!

**Comment by brendt** [comment]
I'm not sure how to handle it yet, feel free to pitch any API ideas in this comment :)

**Comment by yassiNebeL** [comment]
@brendt which class I need to tackle when doing a form submission with files, _./Http/GenericRequest.php_ or the one in the repo _./HttpClient/GenericHttpClient_ or both.

From my understanding, `GenericHttpClient` is the appropriate class, because it handles CRUD methods.

**Comment by brendt** [comment]
Maybe we should first think about the API before diving into implementations? What do you think this feature should look like?

**Comment by yassiNebeL** [comment]
Let's assume we are a form submission operation, where the user is uploading an avatar.

The controller will look like so:
```php
class AvatarController
{
    public function store(AvatarRequest $request)
    {
        $user = // the authentication is still in progress, typically, we need to add a new method to the interface
        $user->avatar_path = $request->avatar->path();
        $user->save();
        
        return new Redirect(…);
    }
}
```

Then, the `AvatarRequest` class, which, in the other hand, defines an objet of the `UploadedFile` class:
```php
class AvatarRequest implements Request
{
    use BaseRequest;
    
    public Upload $avatar;
}
```

Finally, this is the `Upload` class, and it's not finished yet because we will improve it according to the needs:
```php
use SplFileObject ;
final readonly class Upload extends \SplFileInfo 
{
    public function __construct(
        public string $name,
        public string $path,
        public ?string $mimeType = null,
        public ?int $error = null
    ) {
        
        // Do some stuffs, checking file...

        parent::__construct($path);
    }

    public function move(string $directory, ?string $name = null)
    {
        // implement logic behind move_uploaded_file() function
    }
}
```

@brendt, if you're okay with this approach, I'll send a PR, also if you agree to target the `Http` folder instead of `HttpClient`

Regards

**Comment by brendt** [comment]
Yeah, I like this :)

**Comment by brendt** [comment]
And indeed, this belongs in Http

**Comment by yassiNebeL** [comment]
I tried to create an enum for mime types, I found it a bit hard because there are some extensions that start with number like 3gp...So, I decided to guess the mime type using [http://php.net/finfo](finfo), I think it's more appropriate to guess the mime type instead of look for it.

Furthermore, I need to add some methods to the GenericRequest, and perform some additional tests.

**Comment by brendt** [comment]
@yassiNebeL could you push a draft PR?

**Comment by brendt** [comment]
I've added some stuff myself: the PSR files array is now already mapped onto the object. We still need to map individual properties though: #370 

However, I'm going to close this issue because at least files are accessible now, which is all we need for alpha1
