### ISSUE TITLE
Checkup on all subsplit components

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#318]
We need to make sure all subsplits have the right dependencies and work standalone.

**Comment by brendt** [comment]
TODO: 

- [ ] View config is in the wrong component

**Comment by aidan-casey** [comment]
Individual test runs is now happening in CI on main. I am working with Coveralls to get [Carryforward flags](https://coveralls.io/better-monorepo-support) enabled for us so we can track individual coverage on each package instead of just the overall package coverage.

Next step, I think, would be to only run the test suite necessary for a PR submitted (e.g., if the database code is changed, don't test the mapper code).
