### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#47]
A commonly used pattern in Tempest is not to rely on inheritance when it doesn't make sense. Instead we provide interfaces with a default implementation via traits.

One thing to consider with this pattern are naming conventions. Right now, it's the following:

- The interface has the shortest name, as they are used often in user's code. eg `Router`, `CommandBus`, …
- The trait is always prefixed with `Base`: `BaseRouter`, `BaseCommandBus`, …
- A default framework implementation — if needed — is prefixed with `Generic`: `GenericRouter`, `GenericCommandBus`. These classes should never be used in user's code directly.

The two most important names are the interface name and trait name. I'm totally on board with the interface being the shortest, but what about traits? I don't find `Base` to be very intuitive. A couple of alternatives:

- Prefix with `Is`: `IsRouter`, `IsCommandBus`
- Suffix with `Trait`: `RouterTrait`, `CommandBusTrait`

Would like some input :)

---

After some discussion, we've decided to rename the following traits:

- `BaseView`  > `IsView`
- `BaseModel` > `IsModel`
- `BaseConsoleInput` > `HandlesConsoleInput`
- `BaseConsoleOutput` > `HandlesConsoleOutput`
- `BaseResponse` > `IsResponse`
- `BaseRequest` > `IsRequest`
- `BaseConsoleFormatter` > `FormatsConsoleOutput`

**Comment by brendt** [comment]
@aidan-casey your opinion is appreciated :)

**Comment by aidan-casey** [comment]
I agree, this seems worth changing for clarity. I don't like including the type (trait) in the name as a suffix because we aren't doing that elsewhere and for reasons similar to this [article](https://blog.nette.org/en/prefixes-and-suffixes-do-not-belong-in-interface-names) on interface naming.

I don't necessarily mind the `Is{Something}` convention. It's tidy and consistent.

Now this does pretty much tie the class role to the trait name. Are there any scenarios you can think of where that wouldn't be true? For example, Laravel has `MustVerifyEmail` or `InteractsWithQueue`.

For the sake of argument I'll throw that out there as a third option: describing the functionality gained by adding it.

Side note, does it make sense to revise the naming of "generic" (default) implementations? I tend toward specificity like that article defines myself, though I do recognize that may be somewhat awkward with things you'd never change like a router.

**Comment by brendt** [comment]
> Side note, does it make sense to revise the naming of "generic" (default) implementations?

Definitely, but I don't want them to share the same name as the interface, as that is confusing to end users when trying to reference them. 

> For the sake of argument I'll throw that out there as a third option: describing the functionality gained by adding it.

It might be a good idea, although I sometimes find Laravel's trait names not 100% accurate. Eg. `MustVerifyEmail` to me is the name of an interface, `VerifiesEmail` would be the name of the trait 

FYI, this is the current list:

<img width="737" alt="Screenshot 2024-02-19 at 11 12 00" src="https://github.com/tempestphp/tempest-framework/assets/6905297/c78bd029-541e-44ef-b602-ae6035c807db">

**Comment by aidan-casey** [comment]
> I don't want them to share the same name as the interface, as that is confusing to end users when trying to reference them.

Agreed. So make it _how_ it is implemented? For example, `InMemoryCommandBus`.

> FYI, this is the current list

I think `Is{Something}` makes most sense for traits that define what you are working with (e.g., `IsModel`).

There may be room for some functionality based naming in addition to that though. For example, does `IsConsoleInput` actually make sense over something like `HandlesConsoleInput`?

**Comment by brendt** [comment]
- `BaseView`  > `View` and `IsView`
- `BaseModel` > `Model` and `IsModel`
- `BaseConsoleInput` > `ConsoleInput` and `HandlesConsoleInput`
- `BaseConsoleOutput` > `ConsoleOutput` and `HandlesConsoleOutput`
- `BaseResponse` > `Response` and `IsResponse`
- `BaseRequest` > `Request` and `IsRequest`
- `BaseConsoleFormatter` > `ConsoleFormatter` and `FormatsConsole` > I'm not sure whether Tempest should expose this interface, or whether it's a purely internal class that doesn't require an interface

WDYT? Feel free to make adjustments

**Comment by aidan-casey** [comment]
Seems reasonable to me!
