### ISSUE TITLE
Discussion on the Framework’s Database Model Architecture

### ISSUE THREAD

**Issue by nacholibre** [tempestphp/tempest-framework#783]
First, I want to commend you on the amazing work you’ve done with this framework! I also really enjoy your breakdowns of new PHP features on your personal blog—they’re insightful and a pleasure to read.

I wanted to start a discussion about the database model architecture in your framework. Specifically, I’d like to share some thoughts on the current approach and see what others think.

Here’s an example that illustrates the pattern I’m referring to:
```php
final class Document implements DatabaseModel
{
    use IsDatabaseModel;
    
    public function __construct(
        #[Length(min: 1, max: 120)]
        public string $title,
    ) {}
}


$document = new Document;
$document->setTitle('Financial report');
$document->save();
```

Personally, I’ve always found it counterintuitive to mix the model itself with database persistence logic. When I think about objects in programming, I often draw inspiration from real-world objects and their interactions.

For instance, if we imagine a real-world document (a piece of paper), it doesn’t inherently know how to save itself, delete itself, or query for other documents. It’s just a document—a passive entity. The responsibility for persistence typically belongs to an external system, like a filing cabinet or database service, not the document itself.

From this perspective, giving models the ability to save, query, or delete themselves seems to blur the lines between responsibilities. This can lead to tightly coupled code and potentially less maintainable designs.

And what about when you need more control? For example create/update/delete 100 documents with only one query, how should that work?

I’d love to hear your thoughts on this architectural decision and whether alternatives, such as separating models and persistence (e.g., repositories or data mappers), might align better with the single responsibility principle and other design paradigms.

**Comment by aidan-casey** [comment]
So, @brendt is definitely going to be the better person to respond to this, but I just wanted to quickly bring something to your attention.

Tempest actually supports both options, which is part of the beauty of the framework. Under the hood, the query builder is simply using a mapper. There is no obligation to make the mapper the entity itself if you don't want to.

The bottom line? Want to keep on using Laravel-esque models? No problem. Prefer mappers? We have you covered.

Here's a quick example from the docs:

```php
use Tempest\Database\Query;
use function Tempest\map;

// Select all books and map them to a book object.
$books = map(new Query(<<<SQL
    SELECT * 
    FROM Book
    LEFT JOIN …
    HAVING … 
SQL))->collection()->to(Book::class);

// Get a single book.
$books = map(new Query(<<<SQL
    SELECT * 
    FROM Book
    LIMIT 1
SQL))->to(Book::class);
```

**Comment by brendt** [comment]
It's a very interesting question! Thanks for asking.

Think of `DatabaseModel` and `IsDatabaseModel` as completely optional — as Aidan mentioned before. The mapper — the ORM — can work with any type of object, they don't have to implement anything. The mapper also supports going the other way around, from models to queries. However, there are _some_ limitation to it:

- Mapping models to queries (for inserts and updates): we _do_ currently check for the `DatabaseModel` interface. This could be refactored, because the only method/property we actually need to know about is the id, and even that could be inferred without an interface.
- Delete queries can't be performed via the mapper.
- The mapper is somewhat limited in what it can do: it can load relations via joins, but it relies on a very specific naming convention, so manually mapping complex queries to objects becomes a pain if you don't implement `DatabaseModel`.

The ORM is one of the hardest parts of the framework to get right. We chose early on to have a fairly simplistic approach for simple selects, updates, inserts, and deletes via the `IsDatabaseModel` trait, specifically for people coming from Laravel. Whenever people need something more complex, they are free to implement, for example, their custom repository classes, and use the mapper (or not) to map query results to objects and back. 

It's the easy way out for now, and maybe we could improve on it in the future. We need to be realistic though about the limited time we have to work on Tempest: if we try to design something right now, it probably won't be as good as we'd like it to be. It'll need more time and resources to come up with something that's extremely user-friendly, performant, and has support for enough database engines.

If you're interested in reading some more about the thought process that already went into this, you can check out this issue: https://github.com/tempestphp/tempest-framework/issues/103

I'm going to close this one, but feel free to keep the conversation going!

**Comment by jorisvaesen** [comment]
I share the concerns of @nacholibre. I come from the CakePHP world where the separation between tables and entities happened in 3.0 (launched 9 years ago). At that time I advocated the split to ensure separation of concerns en prevent tightly coupled code. Helper methods on the model itself which handles persistence always felt weird and restrictive.

But as @brendt mentioned, there is only limited time and resources and yes, the ORM is one of the most complex parts of a framework. But I also think it's one of the most essential things about a framework that may require a lot of thinking. I also hope the 'looks similar to Laravel' argument doesn't hold over time, since Tempest has its uniqueness.

Just wanted to share this for future reference - keep up the good work!

CakePHP table objects: [https://book.cakephp.org/5/en/orm/table-objects.html](https://book.cakephp.org/5/en/orm/table-objects.html)
CakePHP entities: [https://book.cakephp.org/5/en/orm/entities.html](https://book.cakephp.org/5/en/orm/entities.html)
