### ISSUE TITLE
Run `composer qa` on PR merge

### ISSUE THREAD

**Issue by brendt** [tempestphp/tempest-framework#83]
… and commit codestyle changes automatically to those PR branches.

**Comment by brendt** [comment]
Sidenote: I'm not sure if we can commit to those PR branches, so maybe it should be "run composer qa on main whenever is PR is merged"

**Comment by aidan-casey** [comment]
@brendt - We technically can commit to those branches, but sometimes it's annoying if you commit and then try and re-commit (because there are changes to be pulled).

For now, I have set up two workflows Quality Assurance (run on PRs) and Quality Control (run on push to main). The primary difference between the two being that QC will push fixed styling, while QA will simply fail if the styling doesn't match.

The push styling is currently failing due to permissions on the actions. We can also update permissions to allow writing to a PR and automatically leave a comment to the user to run `composer qa` if you want to. That just requires a repo admin to set up.

As we have coveralls up, I will update the actions to generate all that.

**Comment by brendt** [comment]
Great idea about splitting it up, I love it!

Could you tell me which permissions specifically are needed and where I need to configure them?

**Comment by aidan-casey** [comment]
**Settings > Actions > General > Workflow Permissions**
Enable _Read and write permissions_
Enable _Allow GitHub Actions to create and approve pull requests_

And then make sure no one pushes any ridiculous actions going forward. 😉

**Comment by brendt** [comment]
Ok, should be done now :)

**Comment by aidan-casey** [comment]
@brendt - With coveralls enabled now, I am going to close this issue. I may add an additional step to the workflow to comment on the PR if styling fails, but we can address that separately.

**Comment by aidan-casey** [comment]
@brendt - With coveralls enabled now, I am going to close this issue. I may add an additional step to the workflow to comment on the PR if styling fails, but we can address that separately.
